[package]
name = "y3"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.174"
memmap = "0.7.0"

[dev-dependencies]
criterion = "0.6.0"
tempfile = "3.20.0"

[[bench]]
name = "src_reader"
path = "benches/src_reader.rs"
harness = false
